# Generated by Django 4.2 on 2023-04-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BookManagementApp", "0002_alter_book_bookno"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuedbook",
            name="status",
            field=models.CharField(
                choices=[("Issued", "Issued"), ("Return", "Return")],
                default="Issued",
                max_length=20,
            ),
        ),
    ]
