# Generated by Django 4.2 on 2023-04-26 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BookManagementApp", "0003_issuedbook_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issuedbook",
            options={"ordering": ["status"]},
        ),
        migrations.AddField(
            model_name="issuedbook",
            name="requested_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 4, 26, 4, 52, 58, 141071, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="issuedbook",
            name="issued_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="issuedbook",
            name="status",
            field=models.CharField(
                choices=[
                    ("Issued", "Issued"),
                    ("Return", "Return"),
                    ("Requested", "Requested"),
                ],
                default="Issued",
                max_length=20,
            ),
        ),
    ]
