# Generated by Django 4.2 on 2023-04-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BookManagementApp", "0005_alter_issuedbook_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuedbook",
            name="issued_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
