# Generated by Django 4.2 on 2023-04-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BookManagementApp", "0007_book_publication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuedbook",
            name="requested_date",
            field=models.DateField(auto_now=True),
        ),
    ]
