# Generated by Django 4.2 on 2023-06-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BookManagementApp", "0008_alter_issuedbook_requested_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuedbook",
            name="issued_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
